### ISSUE TITLE
Investigate bug with 'callbackNo'

### ISSUE THREAD

**Issue by mike-audi** [tiki/spam_card#14]
```
VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Closure call with mismatched arguments: function 'DecisionStrategySpam.addSpamCards.<anonymous closure>.<anonymous closure>'
Receiver: Closure: (dynamic) => Future<bool>
Tried calling: DecisionStrategySpam.addSpamCards.<anonymous closure>.<anonymous closure>()
Found: DecisionStrategySpam.addSpamCards.<anonymous closure>.<anonymous closure>(dynamic) => Future<bool>
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85:9)
#2      CardService.callbackNo (package:tiki_spam_cards/src/card/card_service.dart:29:64)
#3      ScreenController.removeCard (package:tiki_decision/src/screen/screen_controller.dart:14:35)
#4      ScreenViewLayout.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:tiki_decision/src/screen/screen_view_layout.dart:32:63)
#5      _ScreenViewWidgetCardState.onDragEnd (package:tiki_decision/src/screen/screen_view<…>
```

**Comment by mike-audi** [comment]
Fixed thru a combination of 

https://github.com/tiki/spam_card/releases/tag/0.0.9
https://github.com/tiki/decision/releases/tag/0.0.10
https://github.com/tiki/data/releases/tag/0.0.7
